### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

vector = np.random.rand(10)
print(vector)

[0.19950441 0.41740636 0.92265931 0.2713606  0.64587109 0.50642508
 0.769037   0.77444451 0.20337225 0.35974518]


In [12]:
def generate_matrix(rows, cols, start, step):
    total = rows * cols
    data = np.array([start + i * step for i in range(total)])
    return data.reshape(rows, cols)

matrix = generate_matrix(3, 3, start=11, step=3)
print(matrix)

[[11 14 17]
 [20 23 26]
 [29 32 35]]



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [20]:
print('1:', (vector + 10).round(2));
print('\n');
print('2:', vector * 2);
print('\n');
print('3:', vector ** 2);

1: [10.2  10.42 10.92 10.27 10.65 10.51 10.77 10.77 10.2  10.36]


2: [0.39900881 0.83481271 1.84531862 0.54272119 1.29174217 1.01285016
 1.53807399 1.54888903 0.40674451 0.71949036]


3: [0.03980201 0.17422807 0.85130021 0.07363657 0.41714946 0.25646636
 0.5914179  0.59976431 0.04136027 0.1294166 ]


Тут явно цикли не використовуються, але дані операції звісно під капотом використовують цикли.


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [21]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [24]:
result_matrix = np.dot(A, B)
print(result_matrix)

[[0.232  0.1627 0.2145]
 [0.3061 0.4867 0.633 ]
 [0.1393 0.2261 0.294 ]]


вектор С в даному випадку представлений у вигляді матриці, розмірністю 2х1, в той час як result_matrix має розмірність 3х3, для того щоб виконати множення матриць має виконуватись умова: кількість рядків у result_matrix має = кількості стовпців у С матриці. Дана умова не виконується, отримаємо помилку.

In [26]:
print(np.dot(result_matrix, C))

ValueError: shapes (3,3) and (2,1) not aligned: 3 (dim 1) != 2 (dim 0)

Аналогічно і тут, 3х3 * 2х2 є неможливим, бо 3 != 2.

In [27]:
print(np.dot(result_matrix, D))

ValueError: shapes (3,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [28]:
print(result_matrix.T)

[[0.232  0.3061 0.1393]
 [0.1627 0.4867 0.2261]
 [0.2145 0.633  0.294 ]]


In [35]:
print(vector)
print('\n');
print(vector.T)

[0.19950441 0.41740636 0.92265931 0.2713606  0.64587109 0.50642508
 0.769037   0.77444451 0.20337225 0.35974518]


[0.19950441 0.41740636 0.92265931 0.2713606  0.64587109 0.50642508
 0.769037   0.77444451 0.20337225 0.35974518]


Ніяких змін при транспонування вектора не відбулось. Тому що в даному випадку вектор представлений у вигляді списку, а має бути представлений у вигляді матриці.

In [40]:
column_vector = np.expand_dims(vector, axis=1)
print(column_vector)

[[0.19950441]
 [0.41740636]
 [0.92265931]
 [0.2713606 ]
 [0.64587109]
 [0.50642508]
 [0.769037  ]
 [0.77444451]
 [0.20337225]
 [0.35974518]]


Тепер отримали одновімірну матрицю, яка і є нашим вектором, просто ми її представили у вигляді матриці.

In [41]:
print(column_vector.T)

[[0.19950441 0.41740636 0.92265931 0.2713606  0.64587109 0.50642508
  0.769037   0.77444451 0.20337225 0.35974518]]
